package GivenTools;

import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Arrays;

/**
 * @author chai1
 * @author trw63
 *
 */

public class Peer {
	private String peer_id;
	private String peer_ip;
	private int peer_port;
	
	/**
	 * used in openSocket()
	 */
//	private Socket peerSocket;
//	private DataOutputStream toPeer;
//	private DataInputStream fromPeer;
	
	public Peer(String id, String ip, int port) {
		peer_id = id;
		peer_ip = ip;
		peer_port = port;
	}
	
	public String getPeerID() {
		return peer_id;
	}
	
	public String getPeerIP() {
		return peer_ip;
	}
	
	public int getPeerPort() {
		return peer_port;
	}

	public void tryHandshakeAndDownload(byte[] info_hash, String generatedPeerID) {
		Socket peerSocket;
    	DataOutputStream toPeer;
    	DataInputStream fromPeer;
    	byte[] peersHandshake = new byte[68]; //28 + 20 + 20 ; fixedHeader, info_Hash, peerID
    	
    	System.out.println();
    	System.out.println("Inside tryHandshakeAndDownload in Peer.java...");
    	System.out.println();
    	
	    try {
	    	peerSocket = new Socket(peer_ip, peer_port);
	    	toPeer = new DataOutputStream(peerSocket.getOutputStream());
			fromPeer = new DataInputStream(peerSocket.getInputStream());
			
//			byte[] handshakeHeader = createHandshakeHeader(info_hash, generatedPeerID);
			byte[] handshakeHeader = createHandshakeHeader(info_hash, peer_id); //Try with peer's id
			//Perform handshake?
			toPeer.write(handshakeHeader);
			fromPeer.readFully(peersHandshake, 0, peersHandshake.length);
			
			System.out.println("What I sent.........: " + Arrays.toString(handshakeHeader));
			System.out.println("Response from server: " + Arrays.toString(peersHandshake));

			/**
			 * The peer should immediately respond with his own handshake message, 
			 * 		which takes the same form as yours.
			 * If you received a peer_id in your tracker response,
			 * 		you should check that the peer_id provided by the peer in the handshake matches what you expect.
			 * If it does not, you should close the connection
			 * 
			 * When serving files, you should check the incoming peer’s handshake to verify that the info_hash
			 * 		matches one that you are serving and close the connection if not.
			 * 
			 * 
			 * This is from wiki: If the initiator of the connection receives a handshake in which the peer_id does not match the expected peerid,
			 *  then the initiator is expected to drop the connection.
			 *   Note that the initiator presumably received the peer information from the tracker, 
			 *   which includes the peer_id that was registered by the peer.
			 *   The peer_id from the tracker and in the handshake are expected to match.
			 */
			
			System.out.println("call isEqualByteArray() on my handshake and peersresponse: " + isEqualByteArray(handshakeHeader, peersHandshake));
	
			//Verify hash from peer? close connection if not same
			
			//Download file?
			
			toPeer.close();
	    	fromPeer.close();
	    	peerSocket.close();
	    }
	    catch (IOException e) {
	        System.out.println(e);
	    }
	}
	
	/**
	 * Handshaking between peers begins with byte nineteen followed by the string 'BitTorrent protocol'.
	 ** After the fixed headers are 8 reserved bytes which are set to 0. 
	 * Next is the 20-byte SHA-1 hash of the bencoded form of the info value from the metainfo (.torrent) file.
	 * The next 20-bytes are the peer id generated by the client. 
	 * The info_hash should be the same as sent to the tracker, and the peer_id is the same as sent to the tracker. 
	 * If the info_hash is different between two peers, then the connection is dropped.
	 **/
	private byte[] createHandshakeHeader(byte[] info_hash, String generatedPeerID) {
		ByteArrayOutputStream header = new ByteArrayOutputStream();
		byte[] fixedHeader = {19, 'B','i','t','T','o','r','r','e','n','t',' ', 'p','r','o','t','o','c','o','l',0,0,0,0,0,0,0,0};
		
		try {
			header.write(fixedHeader);
			header.write(info_hash);
			header.write(generatedPeerID.getBytes());
//			System.out.println(Arrays.toString(header.toByteArray()));
		} catch (IOException e) {
			System.out.println("Failed to generate handshake header.");
		}
		
		return header.toByteArray();
	}
	
	//Maybe create another class to do handshake...? 
	@SuppressWarnings("unused")
	private void handshakePeer() {
		
	}
	
	public boolean checkHandshakeResponse(byte[] info_hash, String generatedPeerID, byte[] peersHandshake) {
		byte[] peersHeader;
		byte[] peersInfoHash;
		byte[] peersID;
		return false;
	}
	
	//Use Arrays.equals() if you want to compare the actual content of arrays that contain primitive types values (like byte).
	//Checks if two byte arrays are equal
	public boolean isEqualByteArray(byte[] b1, byte[] b2) {
		if (Arrays.equals(b1, b2)) {
			return true;
		} else {
			return false;
		}
	}
	
	public void printPeer() {
		System.out.println("---"); 
		System.out.println("peerID: " + getPeerID());
		System.out.println("peerIP: " + getPeerIP());
		System.out.println("peerPort: " + getPeerPort());
	}
}